name: graphqldemo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.1.2
  go_router: ^10.1.0
 
 #json
  json_serializable: ^6.7.1
  build_runner: ^2.4.5
  bloc: ^8.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  solutelabs_lint:
    git:
      url: https://github.com/solutelabs/solutelabs_lint
      ref: dev



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
